name: Build-Exe
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        wget -q https://musl.cc/arm-linux-musleabi-cross.tgz
        tar xf arm-linux-musleabi-cross.tgz
        wget -q https://www.netfilter.org/pub/libmnl/libmnl-1.0.5.tar.bz2
        tar xf libmnl-1.0.5.tar.bz2
    - name: Build-libmnl
      run: |
        PATH=$PATH:$GITHUB_WORKSPACE/arm-linux-musleabi-cross/bin
        ./configure --host=arm-linux CC=arm-linux-musleabi-gcc LDFLAGS=-static --prefix="$PWD/out"
        make
        make install
      working-directory: libmnl-1.0.5
    - name: Build
      run: |
        PATH=$PATH:$GITHUB_WORKSPACE/arm-linux-musleabi-cross/bin
        echo $PATH
        ./configure --prefix="$PWD/out" --host=arm-linux CC=arm-linux-musleabi-gcc MNL_CFLAGS="-I$PWD/libmnl-1.0.5/out/include" MNL_LIBS="-L$PWD/libmnl-1.0.5/out/lib -lmnl" LDFLAGS=-static
        make
        make install
    - uses: actions/upload-artifact@v4
      with:
        name: ethtool
        path: out
